name: Python CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar Poetry
      run: pip install poetry

    - name: Instalar dependencias
      run: poetry install

    - name: Ejecutar tests con cobertura mínima
      run: poetry run pytest --cov=bot --cov-report=term --cov-fail-under=90
    

    - name: Verificar tipado con mypy
      run: poetry run mypy .

    - name: Verificar formato con ruff
      run: poetry run ruff check .

    - name: Verificar formateo con ruff format
      run: poetry run ruff format --check .

